# Site settings
title: Goncalves Lab
description: "Website of the Goncalves Lab at the DKFZ"
url: "http://localhost:4000"
author:
  name: "Angela Goncalves"
  email: "a.goncalves @ dkfz"

# Build settings
markdown: kramdown
source: .
destination: ./_site
#paginate: 8
#paginate_path: "/archive/page:num/"

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins: [jekyll-paginate]

# Plugins
gems:
#  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

collections:
  - group_members
